### PR TITLE
Added Victor Rabesquine

### PR DESCRIPTION
**Pull request by jgallias**

### CODE REVIEW

**Comment by mjke** [comment]
hey @jgallias , we should make a README on the repo about this, but for now here's a quick summary of update steps needed to add/remove a lab member:
- [ ] add them to `authors.yml`
- [ ] prepare and add a `bio-<lastname>.jpg` photo (called an `avatar` in the yml)
- [ ] activate relevant python2.7 conda env and run `utils/update_papers_people.sh` to populate relevant collections, etc
- [ ] verify it all looks good locally on your localhost:4000 using `bundle exec jekyll serve`

**Comment by mjke** [comment]
@jgallias per the list above, could you complete the remaining steps and lmk when ready for my review?

**Review by mjke — CHANGES_REQUESTED** [review]
@jgallias as mentioned in the main PR comment thread, could you pls go through the steps there and lmk when ready

**Comment by jgallias** [comment]
This is replaced by: https://github.com/keiserlab/keiserlab.github.io/pull/2

**Pull request closed without merging**
